// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHJRJ8BaSAuZ2KDimeKvuyNXd7ej0Eto',
    appId: '1:158174198597:web:f1b3449477f0cc1adb1c2c',
    messagingSenderId: '158174198597',
    projectId: 'chat-e437a',
    authDomain: 'chat-e437a.firebaseapp.com',
    storageBucket: 'chat-e437a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWwL8BScDiYvh8YDeB-mjYmvmbUFr4iE',
    appId: '1:158174198597:android:d52ed5ec20383bf6db1c2c',
    messagingSenderId: '158174198597',
    projectId: 'chat-e437a',
    storageBucket: 'chat-e437a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfY4eNkT6nL_LgLpTyqILmREHHbBKl0UY',
    appId: '1:158174198597:ios:dc486ddf1ebfb1a1db1c2c',
    messagingSenderId: '158174198597',
    projectId: 'chat-e437a',
    storageBucket: 'chat-e437a.appspot.com',
    iosClientId: '158174198597-lgjnaq3v0d9uh8v6l8k9eejh02bl5oro.apps.googleusercontent.com',
    iosBundleId: 'dk.tbysys.secureSoftwareSynopsis',
  );
}
